name: medical_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  flutter_local_notifications: "^0.3.0"
  font_awesome_flutter: 7.0.0
  url_launcher: "^3.0.2"
  barcode_scan: "^0.0.4"
#  map_view: "0.0.14"
  google_maps_webservice: "^0.0.5"
  flutter_redux: "^0.5.1"
  redux: "^3.0.0"
  speech_recognition:
      git: "https://github.com/biscuitrainbow/speech_recognition.git"
  uuid: 1.0.3
  http: ^0.11.3+17
  shared_preferences: ^0.4.2
  #sqflite: "^0.10.0"
  path_provider: "^0.4.1"
  flutter_slidable: "^0.1.0"
  location: "^1.3.4"
  intl: "^0.15.6"
  dio: 1.0.0
#  permission_handler: '^1.0.1'
  permission: ^0.0.9
  flutter_launcher_icons: "^0.5.2"
  flutter_map: ^0.0.1
  google_maps_flutter:
     git:
       url: git://github.com/flutter/plugins
       path: packages/google_maps_flutter
#  geolocator: '^1.0.0'
  side_header_list_view: "^0.0.3"
  fluttertoast: ^2.0.7

#  speech_reg:
#      path: "../../../biscuitrainbow/code/flutter_plugin/speech_reg/"

# dev_dependencies:
#   # flutter_test:
#   #   sdk: flutter

  # dependency_overrides    

flutter_icons:
  image_path: "assets/icons/med_icon_1024.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/camt_logo.jpg
    - assets/imgs/nrct_logo.jpg
    - assets/imgs/pharmacy_logo.png
    - assets/icons/med_icon_circle.png
    - assets/icons/med_icon_only.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Kanit
        fonts:
          - asset: fonts/Kanit-Black.ttf
            weight: 900
          - asset: fonts/Kanit-ExtraBold.ttf
            weight: 800
          - asset: fonts/Kanit-Bold.ttf
            weight: 700
          - asset: fonts/Kanit-Semibold.ttf
            weight: 600
          - asset: fonts/Kanit-Medium.ttf
            weight: 500
          - asset: fonts/Kanit-Regular.ttf
            weight: 400
          - asset: fonts/Kanit-Light.ttf
            weight: 300
          - asset: fonts/Kanit-Light.ttf
            weight: 200
          - asset: fonts/Kanit-Thin.ttf
            weight: 100
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
